image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev

stages:
  - build
  - Dbscan_test
  - Dbscan_memory_test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"

Dbscan_test:
  stage: Dbscan_test
  script:
    - cd build
    - ../tests/run.sh ./clusters

Dbscan_memory_test:
  stage: Dbscan_memory_test
  script:
    - apt-get update && apt-get install -y valgrind
    - ../tests/run.sh ./clusters --memcheck
