image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev

stages:
  - build
  - Dbscan_test
  - Dbscan_memory_test
  - Forel_test
  - Forel_memory_test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"

Dbscan_test:
  stage: Dbscan_test
  script:
    - ./tests/run_Dbscan.sh ./build/src/clusters

Dbscan_memory_test:
  stage: Dbscan_memory_test
  script:
    - apt-get update && apt-get install -y valgrind
    - ./tests/run_Dbscan.sh ./build/src/clusters --memcheck

Forel_test:
  stage: Forel_test
  script:
    - ./tests/run_Forel.sh ./build/src/clusters

Forel_memory_test:
  stage: Forel_memory_test
  script:
    - apt-get update && apt-get install -y valgrind
    - ./tests/run_Forel.sh ./build/src/clusters --memcheck
